// ─────────────────────────────────────────────────────────────
// DataDeck Agent — styled task-report email
//
// Renders a brand-styled HTML email (inline CSS, email-client safe) and sends
// it best-effort via Resend (RESEND_API_KEY). The rendered HTML is always
// written to the project folder as email.html, so the report exists whether or
// not a provider is configured. No secret values are ever logged.
// ─────────────────────────────────────────────────────────────
export interface EmailStat { label: string; value: string | number; }
export interface EmailLink { label: string; url: string; }
export interface EmailData {
  datasetName: string;
  headline: string;
  stats: EmailStat[];
  links: EmailLink[];
  siteUrl?: string;           // deployed multipage site (Vercel), if any
  generatedAt: string;
}

const INK = '#0C1D1B', AQUA6 = '#0E9C8E', AQUA1 = '#DCF5F1', MUT = '#5C7370', LINE = '#DDE8E7', ACC = '#F5C948';

export function renderEmailHtml(d: EmailData): string {
  const esc = (s: unknown) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const statCells = d.stats.map((s) => `
    <td style="padding:10px 14px;border:1px solid ${LINE};border-radius:10px;background:#ffffff" align="center">
      <div style="font:700 20px Segoe UI,Arial,sans-serif;color:${INK}">${esc(s.value)}</div>
      <div style="font:400 12px Segoe UI,Arial,sans-serif;color:${MUT};margin-top:2px">${esc(s.label)}</div>
    </td>`).join('<td style="width:8px"></td>');
  const linkItems = d.links.map((l) => `
    <tr><td style="padding:6px 0;font:400 14px Segoe UI,Arial,sans-serif">
      <a href="${esc(l.url)}" style="color:${AQUA6};text-decoration:none">&rarr; ${esc(l.label)}</a>
    </td></tr>`).join('');
  const cta = d.siteUrl ? `
    <tr><td style="padding:22px 0 6px">
      <a href="${esc(d.siteUrl)}" style="background:${AQUA6};color:#fff;text-decoration:none;font:600 15px Segoe UI,Arial,sans-serif;padding:12px 22px;border-radius:10px;display:inline-block">View the interactive report &nbsp;&rarr;</a>
    </td></tr>` : '';

  return `<!doctype html><html><body style="margin:0;background:#F4F6F8;padding:24px">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;background:#fff;border:1px solid ${LINE};border-radius:16px;overflow:hidden">
  <tr><td style="background:${INK};padding:20px 26px">
    <span style="font:700 18px Segoe UI,Arial,sans-serif;color:#fff">DataDeck</span>
    <span style="font:400 13px Segoe UI,Arial,sans-serif;color:${AQUA1};margin-left:8px">task report</span>
  </td></tr>
  <tr><td style="padding:24px 26px 6px">
    <div style="font:700 20px Segoe UI,Arial,sans-serif;color:${INK}">${esc(d.datasetName)} — cleaned &amp; analyzed</div>
    <div style="font:400 14px Segoe UI,Arial,sans-serif;color:${MUT};margin-top:6px">${esc(d.headline)}</div>
  </td></tr>
  <tr><td style="padding:14px 26px 0">
    <table role="presentation" cellpadding="0" cellspacing="0"><tr>${statCells}</tr></table>
  </td></tr>
  <tr><td style="padding:20px 26px 0">
    <div style="font:600 13px Segoe UI,Arial,sans-serif;color:${INK};text-transform:uppercase;letter-spacing:1px">Deliverables</div>
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%">${linkItems}</table>
    ${cta}
  </td></tr>
  <tr><td style="padding:18px 26px 26px">
    <div style="border-left:3px solid ${ACC};background:#fffdf5;padding:10px 14px;border-radius:0 8px 8px 0;font:400 13px Segoe UI,Arial,sans-serif;color:#5b4a13">
      Ambiguous or invalid values were flagged for review, not guessed. See the Cleaning report for the full list.
    </div>
    <div style="font:400 12px Segoe UI,Arial,sans-serif;color:${MUT};margin-top:16px">Generated by the DataDeck Agent · ${esc(d.generatedAt)}</div>
  </td></tr>
</table></td></tr></table></body></html>`;
}

export interface SendResult { sent: boolean; provider: string; id?: string; error?: string; }

/** Best-effort send via Resend. Returns a status; never throws, never logs secrets. */
export async function sendEmail(to: string, subject: string, html: string): Promise<SendResult> {
  const key = process.env.RESEND_API_KEY;
  const from = process.env.EMAIL_FROM || 'DataDeck <onboarding@resend.dev>';
  if (!key) return { sent: false, provider: 'none', error: 'RESEND_API_KEY not set' };
  if (!to) return { sent: false, provider: 'resend', error: 'no recipient (EMAIL_TO not set)' };
  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { authorization: `Bearer ${key}`, 'content-type': 'application/json' },
      body: JSON.stringify({ from, to: to.split(',').map((s) => s.trim()), subject, html }),
    });
    if (!res.ok) return { sent: false, provider: 'resend', error: `HTTP ${res.status}: ${(await res.text()).slice(0, 160)}` };
    const data = (await res.json()) as { id?: string };
    return { sent: true, provider: 'resend', id: data.id };
  } catch (err) {
    return { sent: false, provider: 'resend', error: (err as Error).message };
  }
}

// ── failure notice (agent could not complete — NO silent fallback) ──

export interface FailureInfo {
  datasetName: string;
  source: string;
  project: string;
  stage: string;
  reason: string;
  generatedAt: string;
}

const RED = '#B4231F', REDBG = '#FCEEEE';

/** Styled brand email telling the user the agent hit a problem and did NOT alter their data. */
export function renderFailureEmailHtml(f: FailureInfo): string {
  const esc = (s: unknown) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  return `<!doctype html><html><body style="margin:0;background:#F4F6F8;padding:24px">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;background:#fff;border:1px solid ${LINE};border-radius:16px;overflow:hidden">
  <tr><td style="background:${INK};padding:20px 26px">
    <span style="font:700 18px Segoe UI,Arial,sans-serif;color:#fff">DataDeck</span>
    <span style="font:400 13px Segoe UI,Arial,sans-serif;color:${AQUA1};margin-left:8px">task report</span>
  </td></tr>
  <tr><td style="padding:24px 26px 6px">
    <div style="font:700 20px Segoe UI,Arial,sans-serif;color:${RED}">Couldn't process ${esc(f.datasetName)}</div>
    <div style="font:400 14px Segoe UI,Arial,sans-serif;color:${MUT};margin-top:6px">The DataDeck Agent hit a problem and stopped. Your source file was <b>not changed</b> and nothing was guessed.</div>
  </td></tr>
  <tr><td style="padding:16px 26px 0">
    <div style="border-left:3px solid ${RED};background:${REDBG};padding:12px 14px;border-radius:0 8px 8px 0">
      <div style="font:600 13px Segoe UI,Arial,sans-serif;color:${RED};text-transform:uppercase;letter-spacing:1px">What happened</div>
      <div style="font:400 14px Segoe UI,Arial,sans-serif;color:#5a1a18;margin-top:6px">At the <b>${esc(f.stage)}</b> step: ${esc(f.reason)}</div>
    </div>
  </td></tr>
  <tr><td style="padding:18px 26px 0">
    <div style="font:600 13px Segoe UI,Arial,sans-serif;color:${INK};text-transform:uppercase;letter-spacing:1px">What to do</div>
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%">
      <tr><td style="padding:6px 0;font:400 14px Segoe UI,Arial,sans-serif;color:${INK}">&rarr; Make sure an AI model is configured (a Gemini API key, or Amazon Bedrock access).</td></tr>
      <tr><td style="padding:6px 0;font:400 14px Segoe UI,Arial,sans-serif;color:${INK}">&rarr; Re-add the file to the inbox to try again — the agent will retry a failed dataset.</td></tr>
      <tr><td style="padding:6px 0;font:400 14px Segoe UI,Arial,sans-serif;color:${INK}">&rarr; Details are in <b>${esc(f.project)}/FAILED.md</b>.</td></tr>
    </table>
  </td></tr>
  <tr><td style="padding:18px 26px 26px">
    <div style="font:400 12px Segoe UI,Arial,sans-serif;color:${MUT}">Source: ${esc(f.source)} · Generated by the DataDeck Agent · ${esc(f.generatedAt)}</div>
  </td></tr>
</table></td></tr></table></body></html>`;
}

/** Plain-markdown failure report written to the project folder as FAILED.md. */
export function renderFailureReport(f: FailureInfo): string {
  return [
    `# DataDeck — could not process ${f.datasetName}`, '',
    `_${f.generatedAt}_`, '',
    '> The DataDeck Agent hit a problem and stopped. Your source file was **not changed**,',
    '> and no values were guessed or rule-cleaned. This is a genuine failure notice, not a partial result.', '',
    '## What happened',
    `- **Stage:** ${f.stage}`,
    `- **Reason:** ${f.reason}`,
    `- **Source file:** \`${f.source}\``,
    `- **Project folder:** \`${f.project}\``, '',
    '## What to do',
    '1. Confirm an AI model is configured — a Gemini API key (`GEMINI_API_KEY`) or Amazon Bedrock access.',
    '   This agent reasons about your data with a model; it will not fall back to blind rule-cleaning.',
    '2. Re-add the file to the inbox to try again. A previously failed dataset is retried automatically.',
    '3. If it keeps failing, check the run logs for the underlying error.', '',
  ].join('\n');
}

/** Plain-markdown task report written to the project folder. */
export function renderTaskReport(d: EmailData, extra: { project: string; email: SendResult; site?: string }): string {
  const lines = [
    `# DataDeck task report — ${d.datasetName}`, '',
    `_${d.generatedAt}_`, '',
    `**${d.headline}**`, '',
    '## Summary', ...d.stats.map((s) => `- ${s.label}: ${s.value}`), '',
    '## Deliverables', ...d.links.map((l) => `- [${l.label}](${l.url})`),
    ...(extra.site ? [`- [Interactive report (deployed)](${extra.site})`] : []), '',
    '## Delivery',
    `- Project folder: \`${extra.project}\``,
    `- Email: ${extra.email.sent ? `sent via ${extra.email.provider}` + (extra.email.id ? ` (id ${extra.email.id})` : '') : `not sent (${extra.email.error})`}`,
    `- Site deploy: ${extra.site ? extra.site : 'not deployed'}`,
    '',
  ];
  return lines.join('\n');
}
