// ─────────────────────────────────────────────────────────────
// DataDeck Agent — report rendering
// Cleaning report + pre-analysis report as HTML (with charts),
// plus a plain Markdown summary and a machine-readable JSON.
// ─────────────────────────────────────────────────────────────
import type { CleanResult, PreAnalysis, FlagRecord, FlagReason } from './types';
import { horizontalBarChart, correlationBarChart, COLORS, type BarDatum } from './charts';

const FLAG_TITLES: Record<FlagReason, string> = {
  ambiguous_date: 'Ambiguous dates',
  unmappable_category: 'Labels that need a decision',
  possible_outlier: 'Possible outliers',
  mixed_currency: 'Mixed currencies',
  missing_in_complete_column: 'Missing values in otherwise-complete columns',
  failed_validation: 'Values that failed a validation rule',
  semantic_anomaly: 'Values that look wrong for what the column means',
};

function pageShell(title: string, body: string): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<style>
  :root { color-scheme: light; }
  body { font-family: Inter, system-ui, -apple-system, sans-serif; color: ${COLORS.ink};
         background: #F4F9F8; margin: 0; padding: 32px; line-height: 1.5; }
  .wrap { max-width: 860px; margin: 0 auto; }
  h1 { font-size: 26px; margin: 0 0 4px; }
  h2 { font-size: 18px; margin: 32px 0 12px; border-bottom: 2px solid ${COLORS.primary}; padding-bottom: 6px; }
  h3 { font-size: 15px; margin: 20px 0 6px; }
  .sub { color: ${COLORS.muted}; margin: 0 0 24px; }
  .cards { display: flex; flex-wrap: wrap; gap: 12px; margin: 16px 0; }
  .card { background: #fff; border: 1px solid ${COLORS.line}; border-radius: 10px; padding: 14px 18px; min-width: 120px; }
  .card .n { font-size: 24px; font-weight: 600; }
  .card .l { color: ${COLORS.muted}; font-size: 12px; }
  table { width: 100%; border-collapse: collapse; background: #fff; border: 1px solid ${COLORS.line};
          border-radius: 10px; overflow: hidden; font-size: 13px; margin: 8px 0 4px; }
  th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid ${COLORS.line}; }
  th { background: #EAF6F4; font-weight: 600; }
  tr:last-child td { border-bottom: none; }
  .pill { display: inline-block; padding: 2px 8px; border-radius: 999px; font-size: 11px; font-weight: 600; }
  .pill.flag { background: #FFF4CC; color: #7a5b00; }
  .pill.ok { background: #E4F6EE; color: #1E7A4C; }
  .muted { color: ${COLORS.muted}; }
  ul.hi { background:#fff; border:1px solid ${COLORS.line}; border-radius:10px; padding:14px 14px 14px 32px; }
  figure { margin: 8px 0 20px; }
  .note { background:#EAF6F4; border-left:4px solid ${COLORS.primary}; padding:10px 14px; border-radius:6px; }
  footer { margin-top: 40px; color: ${COLORS.muted}; font-size: 12px; }
</style>
</head>
<body><div class="wrap">${body}
<footer>Generated by the DataDeck Agent — a Pro Agent for messy data. This report describes exactly what happened to your file.</footer>
</div></body></html>`;
}

function table(headers: string[], rows: string[][]): string {
  const head = headers.map((h) => `<th>${h}</th>`).join('');
  const body = rows
    .map((r) => `<tr>${r.map((c) => `<td>${c}</td>`).join('')}</tr>`)
    .join('');
  return `<table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`;
}

function statCard(n: string | number, label: string): string {
  return `<div class="card"><div class="n">${n}</div><div class="l">${label}</div></div>`;
}

// ── Cleaning report ─────────────────────────────────────────

export function renderCleaningReportHtml(result: CleanResult): string {
  const { profile, changeSummary, flags, cleaned, original, untouchedRowCount } = result;

  const cards = [
    statCard(original.rows.length, 'rows in'),
    statCard(cleaned.rows.length, 'rows out'),
    statCard(profile.columnCount, 'columns'),
    statCard(result.changes.length, 'changes made'),
    statCard(flags.length, 'items flagged'),
    statCard(untouchedRowCount, 'rows untouched'),
  ].join('');

  const changeRows = changeSummary
    .sort((a, b) => b.count - a.count)
    .map((c) => [c.label, String(c.count)]);
  const changeTable = changeRows.length
    ? table(['What changed', 'Count'], changeRows)
    : '<p class="muted">No automatic changes were needed.</p>';

  // Flags grouped by reason.
  const byReason = new Map<FlagReason, FlagRecord[]>();
  for (const f of flags) {
    if (!byReason.has(f.reason)) byReason.set(f.reason, []);
    byReason.get(f.reason)!.push(f);
  }
  let flagsHtml = '';
  if (flags.length === 0) {
    flagsHtml = '<p class="muted">Nothing was ambiguous — no rows need your review. 🎉</p>';
  } else {
    for (const [reason, list] of byReason) {
      const sample = list.slice(0, 10).map((f) => [
        String(f.rowIndex + 1),
        f.column,
        f.value === '' ? '<span class="muted">(blank)</span>' : escapeHtml(f.value),
        escapeHtml(f.why),
      ]);
      flagsHtml += `<h3>${FLAG_TITLES[reason]} <span class="pill flag">${list.length}</span></h3>`;
      flagsHtml += table(['Row', 'Column', 'Value', 'Why it needs you'], sample);
      if (list.length > sample.length) {
        flagsHtml += `<p class="muted">…and ${list.length - sample.length} more.</p>`;
      }
    }
  }

  // Column profile.
  const colRows = profile.columns.map((c) => [
    escapeHtml(c.name),
    c.detectedType,
    `${Math.round(c.fillRate * 100)}%`,
    String(c.unique),
    c.formatIssues.length ? escapeHtml(c.formatIssues.join('; ')) : '<span class="muted">—</span>',
  ]);

  const body = `
<h1>Cleaning report</h1>
<p class="sub">What the DataDeck Agent changed, what it flagged, and why — for <strong>${escapeHtml(original.source ?? 'your file')}</strong>.</p>
<div class="cards">${cards}</div>

<h2>What changed</h2>
${changeTable}
<p class="note">Every change above was applied to a <strong>copy</strong> of your data. Your original file was never modified.</p>

<h2>What needs your review</h2>
<p class="muted">Ambiguous rows were <strong>flagged, not deleted or guessed</strong>. Until you decide, the original values are kept as-is.</p>
${flagsHtml}

<h2>Columns at a glance</h2>
${table(['Column', 'Detected type', 'Filled', 'Unique', 'Notes'], colRows)}

<h2>What was left alone</h2>
<p><strong>${untouchedRowCount}</strong> row(s) were already clean and were passed through untouched — on purpose.</p>
`;
  return pageShell('DataDeck — Cleaning Report', body);
}

// ── Analysis report ─────────────────────────────────────────

export function renderAnalysisReportHtml(analysis: PreAnalysis): string {
  const highlights = `<ul class="hi">${analysis.highlights.map((h) => `<li>${escapeHtml(h)}</li>`).join('')}</ul>`;

  const corr = `<figure>${correlationBarChart(analysis.correlations)}</figure>`;

  const colCharts = analysis.columns
    .map((c) => {
      if (c.distribution.length === 0) return '';
      const data: BarDatum[] = c.distribution.map((d) => ({
        label: d.value,
        value: c.distributionKind === 'histogram' ? d.count : d.count,
        display: c.distributionKind === 'histogram' ? String(d.count) : `${d.count} (${Math.round(d.share * 100)}%)`,
      }));
      const titlePrefix = c.distributionKind === 'histogram' ? 'Distribution of' : 'Top values in';
      let statLine = '';
      if (c.numeric) {
        statLine = `<p class="muted">count ${c.numeric.count} · missing ${c.numeric.missing} · min ${c.numeric.min} · max ${c.numeric.max} · mean ${c.numeric.mean} · median ${c.numeric.median} · std ${c.numeric.stdDev}</p>`;
      } else {
        statLine = `<p class="muted">${c.unique} unique value(s) · missing ${c.missing}</p>`;
      }
      return `<h3>${escapeHtml(c.name)} <span class="muted">(${c.type})</span></h3>${statLine}<figure>${horizontalBarChart(`${titlePrefix} ${c.name}`, data)}</figure>`;
    })
    .join('');

  const body = `
<h1>Pre-analysis report</h1>
<p class="sub">A first look at your cleaned data — so you start the real analysis already oriented.</p>

<h2>Highlights</h2>
${highlights}

<h2>Relationships between columns</h2>
<p class="muted">The strongest correlations, ranked. Aquamarine = move together, orange = move in opposite directions.</p>
${corr}

<h2>Column by column</h2>
${colCharts || '<p class="muted">No columns to chart.</p>'}
`;
  return pageShell('DataDeck — Pre-Analysis Report', body);
}

// ── Plain summaries ─────────────────────────────────────────

export function renderMarkdownSummary(result: CleanResult, analysis: PreAnalysis): string {
  const lines: string[] = [];
  lines.push(`# DataDeck cleaning summary`);
  lines.push('');
  lines.push(`**File:** ${result.original.source ?? 'your file'}`);
  lines.push('');
  lines.push(`- Rows: ${result.original.rows.length} in → ${result.cleaned.rows.length} out`);
  lines.push(`- Columns: ${result.profile.columnCount}`);
  lines.push(`- Changes made: ${result.changes.length}`);
  lines.push(`- Items flagged for review: ${result.flags.length}`);
  lines.push(`- Rows left untouched: ${result.untouchedRowCount}`);
  lines.push('');
  lines.push(`## What changed`);
  if (result.changeSummary.length === 0) lines.push('- Nothing needed fixing.');
  for (const c of [...result.changeSummary].sort((a, b) => b.count - a.count)) {
    lines.push(`- ${c.label}: ${c.count}`);
  }
  lines.push('');
  lines.push(`## What needs your review`);
  if (result.flags.length === 0) lines.push('- Nothing — no ambiguous rows. 🎉');
  const byReason = new Map<string, number>();
  for (const f of result.flags) byReason.set(FLAG_TITLES[f.reason], (byReason.get(FLAG_TITLES[f.reason]) ?? 0) + 1);
  for (const [reason, count] of byReason) lines.push(`- ${reason}: ${count}`);
  lines.push('');
  lines.push(`## First look`);
  for (const h of analysis.highlights) lines.push(`- ${h}`);
  lines.push('');
  return lines.join('\n');
}

export function buildSummaryJson(result: CleanResult, analysis: PreAnalysis): Record<string, unknown> {
  return {
    source: result.original.source ?? null,
    rowsIn: result.original.rows.length,
    rowsOut: result.cleaned.rows.length,
    columns: result.profile.columnCount,
    changesMade: result.changes.length,
    changeSummary: result.changeSummary,
    itemsFlagged: result.flags.length,
    flags: result.flags,
    untouchedRows: result.untouchedRowCount,
    columnProfiles: result.profile.columns,
    analysis: {
      highlights: analysis.highlights,
      correlations: analysis.correlations,
      columns: analysis.columns.map((c) => ({
        name: c.name, type: c.type, missing: c.missing, unique: c.unique, numeric: c.numeric ?? null,
      })),
    },
  };
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export { FLAG_TITLES };
